---
- name: Update all systems and restart if needed only if updates are available
  hosts: all
  become: yes
  tasks:
    - name: Check for available updates (apt)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: 'no'   # hanya update cache, tidak upgrade
        cache_valid_time: 3600
      register: apt_updates
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"

    - name: Update apt systems if updates are available
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_facts['os_family'] == "Debian" and apt_updates is not failed

    - name: Check if restart is needed on Debian based systems
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_facts['os_family'] == "Debian" and apt_updates is not failed

    - name: Restart Debian based system if required
      ansible.builtin.reboot:
      when: ansible_facts['os_family'] == "Debian" and reboot_required_file.stat.exists
