---
- name: Update all systems and restart if needed only if updates are available
  hosts: all
  become: yes
  tasks:
    - name: Check for available updates (apt)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: 'no'   # hanya update cache, tidak upgrade
        cache_valid_time: 3600
      register: apt_updates
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"
